server:
  port: 8080

app:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5555/testdb
    password: postgres
    maximum-pool-size: 30
    username: postgres
